filebeat.inputs:

- type: filestream
  enabled: true
  paths:
    - {{LOG_FILE}}
  fields:
      componentName: {{COMPONENT}}
      env: {{ENV}}
      logType: {{LOG_TYPE}}
      appLang: {{APP_LANG}}
{% if LOG_TYPE == "json" %}
  json.keys_under_root: true
{% endif %}

{% if APP_LANG == "java" %}
  multiline.pattern: '^[0-9][0-9][0-9][0-9]'
  multiline.negate: true
  multiline.match: after
{% endif %}
{% if APP_LANG == "python" %}
  include_lines:
    - '^\[2'
{% endif %}

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1

setup.kibana:


output.logstash:

  hosts: ["logstash.roboshop.internal:5044"]


processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

